---
micronaut:
    application:
        name: producerApp
netty:
  default:
    allocator:
      max-order: 3
jackson:
    serialization:
        writeDatesAsTimestamps: false
---
kafka:
    bootstrap:
        servers: localhost:9092
